### ISSUE TITLE
PlatformerSaves triggers Prism Menu's Macro Editor

### ISSUE THREAD

**Issue by slideglide** [0x5abe/PlatformerSaves#2]
Prism Menu has the Macro Editor feature, where you can fix inaccuracies in macros. However, if you click on "Continue" in PlatformerSaves, Prism Menu's Macro Editor UI appears after starting the level, even when Macro Editor is disabled. Which the expected behavior is that the Macro Editor UI shouldn't appear.

Here is a (low quality) video of it:
https://github.com/0x5abe/PlatformerSaves/assets/68702247/1b230dbc-6ed9-4ffc-9cae-96961ecad5b6

**Comment by 0x5abe** [comment]
Fixed!
